# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/mb_block_axi_smc_2.xci
# IP: The module: 'mb_block_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/bd_d80c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_1/bd_d80c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_2/bd_d80c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_3/bd_d80c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_4/bd_d80c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_5/bd_d80c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_6/bd_d80c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_7/bd_d80c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_8/bd_d80c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_9/bd_d80c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_10/bd_d80c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_11/bd_d80c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_12/bd_d80c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_1/bd_d80c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_5/bd_d80c_s00a2s_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_6/bd_d80c_sarn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_7/bd_d80c_srn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_8/bd_d80c_sawn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_9/bd_d80c_swn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_10/bd_d80c_sbn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_11/bd_d80c_m00s2a_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/mb_block_axi_smc_2.xci
# IP: The module: 'mb_block_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/bd_d80c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_1/bd_d80c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_2/bd_d80c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_3/bd_d80c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_4/bd_d80c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_5/bd_d80c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_6/bd_d80c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_7/bd_d80c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_8/bd_d80c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_9/bd_d80c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_10/bd_d80c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_11/bd_d80c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_12/bd_d80c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_1/bd_d80c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_5/bd_d80c_s00a2s_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_6/bd_d80c_sarn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_7/bd_d80c_srn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_8/bd_d80c_sawn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_9/bd_d80c_swn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_10/bd_d80c_sbn_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_11/bd_d80c_m00s2a_0_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
