# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PYNQ-Z2/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/mb_block/mb_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block || ORIG_REF_NAME==mb_block} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_processing_system7_0_3/mb_block_processing_system7_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_processing_system7_0_3 || ORIG_REF_NAME==mb_block_processing_system7_0_3} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_umeboshi_0_2/mb_block_umeboshi_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_umeboshi_0_2 || ORIG_REF_NAME==mb_block_umeboshi_0_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_smc_2/mb_block_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_smc_2 || ORIG_REF_NAME==mb_block_axi_smc_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_rst_ps7_0_100M_1/mb_block_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_rst_ps7_0_100M_1 || ORIG_REF_NAME==mb_block_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_bram_ctrl_0_2/mb_block_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_bram_ctrl_0_2 || ORIG_REF_NAME==mb_block_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_bram_ctrl_0_bram_1/mb_block_axi_bram_ctrl_0_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==mb_block_axi_bram_ctrl_0_bram_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_bram_ctrl_1_1/mb_block_axi_bram_ctrl_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_bram_ctrl_1_1 || ORIG_REF_NAME==mb_block_axi_bram_ctrl_1_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_bram_ctrl_1_bram_0/mb_block_axi_bram_ctrl_1_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==mb_block_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/mb_block_ooc.xdc
