# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.cache/wt [current_project]
set_property parent.project_path C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/hause/Documents/Vivado/IP [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/new/i2s.sv
  C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/imports/mb_block/mb_block_sv.sv
  C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/new/top.sv
}
add_files C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/bd/mb_block/mb_block.bd
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_processing_system7_0_3/mb_block_processing_system7_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_1/bd_d80c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_2/bd_d80c_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_3/bd_d80c_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_4/bd_d80c_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_5/bd_d80c_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_6/bd_d80c_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_10/bd_d80c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_11/bd_d80c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_12/bd_d80c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_13/bd_d80c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_14/bd_d80c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_15/bd_d80c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_16/bd_d80c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_17/bd_d80c_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_18/bd_d80c_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_19/bd_d80c_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_20/bd_d80c_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_21/bd_d80c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_23/bd_d80c_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_24/bd_d80c_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_25/bd_d80c_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_26/bd_d80c_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_27/bd_d80c_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_28/bd_d80c_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_30/bd_d80c_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_31/bd_d80c_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_32/bd_d80c_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_33/bd_d80c_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_34/bd_d80c_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/bd_0/ip/ip_35/bd_d80c_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_smc_2/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_rst_ps7_0_100M_1/mb_block_rst_ps7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_rst_ps7_0_100M_1/mb_block_rst_ps7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_0_2/mb_block_axi_bram_ctrl_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_0_bram_1/mb_block_axi_bram_ctrl_0_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_1_1/mb_block_axi_bram_ctrl_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_1_bram_0/mb_block_axi_bram_ctrl_1_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/mb_block_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/constrs_1/imports/PYNQ-Z2/PYNQ-Z2 v1.0.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/constrs_1/imports/PYNQ-Z2/PYNQ-Z2 v1.0.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
