# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_0_2/mb_block_axi_bram_ctrl_0_2.xci
# IP: The module: 'mb_block_axi_bram_ctrl_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_0_2/mb_block_axi_bram_ctrl_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_bram_ctrl_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.srcs/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_0_2/mb_block_axi_bram_ctrl_0_2.xci
# IP: The module: 'mb_block_axi_bram_ctrl_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hause/Documents/Vivado/Projects/Takuan/Takuan.gen/sources_1/bd/mb_block/ip/mb_block_axi_bram_ctrl_0_2/mb_block_axi_bram_ctrl_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_bram_ctrl_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
