# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.srcs/sources_1/ip/umeboshi_0/umeboshi_0.xci
# IP: The module: 'umeboshi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_a_bram/osc_a_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==osc_a_bram || ORIG_REF_NAME==osc_a_bram} -quiet] -quiet

# IP: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_b_bram/osc_b_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==osc_b_bram || ORIG_REF_NAME==osc_b_bram} -quiet] -quiet

# XDC: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_a_bram/osc_a_bram_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_b_bram/osc_b_bram_ooc.xdc

# IP: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.srcs/sources_1/ip/umeboshi_0/umeboshi_0.xci
# IP: The module: 'umeboshi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_a_bram/osc_a_bram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==osc_a_bram || ORIG_REF_NAME==osc_a_bram} -quiet] -quiet

# IP: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_b_bram/osc_b_bram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==osc_b_bram || ORIG_REF_NAME==osc_b_bram} -quiet] -quiet

# XDC: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_a_bram/osc_a_bram_ooc.xdc

# XDC: c:/Users/hause/Documents/Vivado/Projects/umeboshiTB/umeboshiTB.gen/sources_1/ip/umeboshi_0/src/osc_b_bram/osc_b_bram_ooc.xdc
